//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UASPBO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CekDokEntities : DbContext
    {
        public CekDokEntities()
            : base("name=CekDokEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Akun> Akuns { get; set; }
        public virtual DbSet<AkunPenyakit> AkunPenyakits { get; set; }
        public virtual DbSet<Penyakit> Penyakits { get; set; }
    }
}
